# Copyright 2026 Jose D. Leonett
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl-3.0).
from odoo import _, api, fields, models
from odoo.exceptions import UserError

RESUPPLY_ROUTE_XMLID = 'mrp_subcontracting.route_resupply_subcontractor_mto'


class MrpSubcontractingChain(models.Model):
    _name = 'mrp.subcontracting.chain'
    _description = 'Subcontracting Chain'
    _inherit = ['mail.thread']
    _order = 'id desc'

    name = fields.Char(required=True, copy=False, readonly=True, default=lambda self: _('New'))
    company_id = fields.Many2one(
        'res.company', required=True, index=True,
        default=lambda self: self.env.company,
    )
    warehouse_id = fields.Many2one(
        'stock.warehouse', string='Warehouse', required=True, check_company=True,
        help='Warehouse whose resupply route was applied to the components sent to the '
             'subcontractor.',
    )
    subcontractor_id = fields.Many2one(
        'res.partner', string='Subcontractor', required=True, index=True,
    )
    final_product_tmpl_id = fields.Many2one(
        'product.template', string='Final Product', required=True, index=True,
        help='The real product at the end of the manufacturing route. Never an intermediate '
             'product generated by this module.',
    )
    anchor_product_tmpl_id = fields.Many2one(
        'product.template', string='Purchased Product', required=True,
        help='The product that appears on the purchase order sent to the subcontractor.',
    )
    operation_name = fields.Char(
        string='Externalized Operation', readonly=True,
        help='Name of the operation that was externalized, as it was at that moment.',
    )
    operation_category_id = fields.Many2one(
        'mrp.routing.operation.category', string='Operation Category', readonly=True,
    )
    bom_ids = fields.One2many(
        'mrp.bom', 'subcontracting_chain_id', string='Bills of Materials', readonly=True,
        context={'active_test': False},
    )
    phantom_product_tmpl_ids = fields.Many2many(
        'product.template', string='Intermediate Products', readonly=True,
        context={'active_test': False},
    )
    component_line_ids = fields.One2many(
        'mrp.subcontracting.chain.component', 'chain_id', string='Components',
    )
    state = fields.Selection(
        [
            ('draft', 'Draft'),
            ('externalized', 'Externalized'),
            ('internalized', 'Internalized'),
        ],
        default='draft', required=True, tracking=True,
    )
    internalized_bom_id = fields.Many2one(
        'mrp.bom', string='Internalized Bill of Materials', readonly=True,
        help='Single Bill of Materials resulting from merging the chain back into an '
             'in-house manufacturing route.',
    )
    pending_internalization_bom_id = fields.Many2one(
        'mrp.bom', string='Pending Internalization', readonly=True,
        help='Bill of Materials revision holding the merged in-house route, waiting for its '
             'Engineering Change Order to be applied.',
    )
    original_workcenter_id = fields.Many2one(
        'mrp.workcenter', string='Original Work Center', readonly=True,
        help='Work center where the operation was performed before being externalized. '
             'Used to restore it on internalization.',
    )
    original_sequence = fields.Integer(readonly=True)
    original_time_mode = fields.Selection(
        [('auto', 'Compute based on tracked time'), ('manual', 'Set duration manually')],
        readonly=True,
    )
    original_time_cycle_manual = fields.Float(readonly=True)
    eco_ids = fields.One2many('mrp.eco', 'subcontracting_chain_id', string='ECOs', readonly=True)
    validated_by_id = fields.Many2one(
        'res.users', string='Applied Without Approval By', readonly=True,
        help='User who chose to apply the Engineering Change Order immediately, skipping the '
             'manual approval circuit.',
    )
    validated_date = fields.Datetime(readonly=True)
    applied_without_eco = fields.Boolean(
        string='Applied Without ECO', readonly=True,
        help='Set when the change was applied through the bulk mode, which does not create an '
             'Engineering Change Order.',
    )
    last_verified_date = fields.Datetime(readonly=True)
    warning_count = fields.Integer(compute='_compute_warning_count')
    purchase_count = fields.Integer(compute='_compute_document_counts')
    receipt_count = fields.Integer(compute='_compute_document_counts')
    resupply_count = fields.Integer(compute='_compute_document_counts')

    @api.depends('state', 'component_line_ids.state')
    def _compute_warning_count(self):
        for chain in self:
            if chain.state != 'externalized':
                # Nothing is delivered to the subcontractor any more, the checklist is history.
                chain.warning_count = 0
                continue
            chain.warning_count = len(
                chain.component_line_ids.filtered(lambda line: line.state == 'warning')
            )

    def _compute_document_counts(self):
        for chain in self:
            products = chain.anchor_product_tmpl_id.product_variant_ids
            purchase_lines = self.env['purchase.order.line'].search([
                ('product_id', 'in', products.ids),
                ('order_id.partner_id', '=', chain.subcontractor_id.id),
            ])
            chain.purchase_count = len(purchase_lines.order_id)
            chain.receipt_count = len(purchase_lines.move_ids.picking_id)
            chain.resupply_count = self.env['stock.picking'].search_count([
                ('partner_id', '=', chain.subcontractor_id.id),
                ('picking_type_id', '=', chain.warehouse_id.subcontracting_resupply_type_id.id),
            ])

    @api.model_create_multi
    def create(self, vals_list):
        for vals in vals_list:
            if vals.get('name', _('New')) == _('New'):
                vals['name'] = self.env['ir.sequence'].next_by_code(
                    'mrp.subcontracting.chain') or _('New')
        return super().create(vals_list)

    # ------------------------------------------------------------------
    # Externalization engine
    # ------------------------------------------------------------------

    @api.model
    def _split_route(self, bom, operation):
        """Split the operations of *bom* around *operation*.

        :return: tuple (operations before, operations after). Both are empty when the whole
            product is externalized (no operation given).
        """
        if not operation:
            return operation.browse(), operation.browse()
        operations = bom.operation_ids.sorted(lambda op: (op.sequence, op.id))
        index = list(operations).index(operation)
        return operations[:index], operations[index + 1:]

    @api.model
    def _split_components(self, bom, operation, operations_before, operations_after):
        """Dispatch the component lines of *bom* into the three stages of the chain.

        Lines that are not linked to any operation are consumed at the very beginning of the
        route, so they follow the first stage that actually exists.
        """
        lines_before = bom.bom_line_ids.filtered(lambda l: l.operation_id in operations_before)
        lines_operation = bom.bom_line_ids.filtered(lambda l: l.operation_id == operation)
        lines_after = bom.bom_line_ids.filtered(lambda l: l.operation_id in operations_after)
        orphan_lines = bom.bom_line_ids - lines_before - lines_operation - lines_after
        if operations_before:
            lines_before |= orphan_lines
        else:
            lines_operation |= orphan_lines
        return lines_before, lines_operation, lines_after

    @api.model
    def _get_phantom_category(self, operation, operations_before, stage):
        """Return the operation category that names the intermediate product of *stage*.

        The suffix of an intermediate product is always the category of the last operation
        actually performed to reach that state.
        """
        if stage == 'pre':
            # The part is handed over to the subcontractor right after the last in-house step.
            return operations_before[-1:].operation_category_id
        return operation.operation_category_id

    @api.model
    def _check_operation_categories(self, operation, operations_before, operations_after):
        missing = self.env['mrp.routing.workcenter']
        if operations_before:
            if not operations_before[-1:].operation_category_id:
                missing |= operations_before[-1:]
        if operations_after and not operation.operation_category_id:
            missing |= operation
        if missing:
            raise UserError(_(
                'The following operations need an Operation Category before they can be used '
                'to name the intermediate products:\n%s',
                '\n'.join('- %s' % name for name in missing.mapped('display_name')),
            ))

    @api.model
    def _get_or_create_phantom_product(self, source_tmpl, category, activate=True):
        """Return the intermediate product for *source_tmpl* at the state of *category*.

        Reuses an existing one when the internal reference already matches, so that running
        the assistant twice never duplicates products.
        """
        default_code = '%s-%s' % (source_tmpl.default_code or source_tmpl.name, category.code)
        existing = self.env['product.template'].with_context(active_test=False).search(
            [('default_code', '=', default_code)], limit=1)
        if existing:
            if activate and not existing.active:
                # A previous cycle archived it on internalization; this one needs it back.
                existing.write({'active': True})
            return existing
        return self.env['product.template'].create({
            'name': '%s - %s' % (source_tmpl.name, category.name),
            'default_code': default_code,
            'type': source_tmpl.type,
            'uom_id': source_tmpl.uom_id.id,
            'uom_po_id': source_tmpl.uom_po_id.id,
            'categ_id': self.env.ref(
                'econovo_mrp_subcontracting_wizard.product_category_subcontracting_phantom').id,
            'tracking': source_tmpl.tracking,
            'company_id': source_tmpl.company_id.id,
            'sale_ok': False,
            'purchase_ok': True,
            'is_subcontracting_phantom': True,
            'active': activate,
        })

    @api.model
    def _relocate_operations(self, operations, target_bom):
        """Recreate *operations* on *target_bom* and return a {source: copy} mapping.

        Operations are recreated instead of reassigned because changing ``bom_id`` on an
        existing operation makes Odoo clear the component lines pointing at it.
        """
        mapping = {}
        for operation in operations:
            mapping[operation] = operation.copy({
                'bom_id': target_bom.id,
                'blocked_by_operation_ids': [(5, 0, 0)],
            })
        return mapping

    @api.model
    def _relocate_component_lines(self, lines, target_bom, operation_mapping=None):
        for line in lines:
            new_operation = (operation_mapping or {}).get(line.operation_id)
            line.copy({
                'bom_id': target_bom.id,
                'operation_id': new_operation.id if new_operation else False,
            })

    @api.model
    def _prepare_chain_bom_vals(self, source_bom, product_tmpl, bom_type,
                                subcontractor=None, activate=True):
        vals = {
            'product_tmpl_id': product_tmpl.id,
            'product_qty': source_bom.product_qty,
            'product_uom_id': source_bom.product_uom_id.id,
            'type': bom_type,
            'company_id': source_bom.company_id.id,
            'consumption': source_bom.consumption,
            'active': activate,
        }
        if bom_type == 'subcontract':
            vals['subcontractor_ids'] = [(6, 0, subcontractor.ids)]
        return vals

    @api.model
    def _get_resupply_route(self):
        """Return the global route that resupplies subcontractors.

        Resolved through Odoo's own helper, which looks the record up by XML id and only
        falls back to its name, so no database id is ever hardcoded. The per-warehouse
        ``subcontracting_route_id`` is deliberately not used: it is created with
        ``product_selectable=False``, which means it carries no meaning on a product and is
        filtered out of ``product.template.route_ids`` on read.
        """
        return self.env['stock.warehouse']._find_or_create_global_route(
            RESUPPLY_ROUTE_XMLID, _('Resupply Subcontractor on Order'))

    def _apply_resupply_route(self, product_tmpls):
        """Add the resupply route to every component sent to the subcontractor."""
        self.ensure_one()
        route = self._get_resupply_route()
        if not route:
            return self.env['product.template']
        updated = self.env['product.template']
        for product_tmpl in product_tmpls:
            if route not in product_tmpl.route_ids:
                product_tmpl.write({'route_ids': [(4, route.id)]})
                updated |= product_tmpl
        return updated

    def _setup_anchor_product(self, seller_price=0.0, add_mto_route=False):
        """Make the purchased product buyable from the subcontractor."""
        self.ensure_one()
        anchor = self.anchor_product_tmpl_id
        routes = [(4, self.env.ref('purchase_stock.route_warehouse0_buy').id)]
        if add_mto_route:
            routes.append((4, self.env.ref('stock.route_warehouse0_mto').id))
        # The whole native flow starts with a purchase order line, which Odoo only accepts
        # for purchasable products.
        anchor.write({'purchase_ok': True, 'route_ids': routes})
        existing_seller = anchor.seller_ids.filtered(
            lambda seller: seller.partner_id == self.subcontractor_id)
        if not existing_seller:
            self.env['product.supplierinfo'].create({
                'partner_id': self.subcontractor_id.id,
                'product_tmpl_id': anchor.id,
                'price': seller_price,
                'company_id': self.company_id.id,
            })

    @api.model
    def _externalize(self, bom, operation, subcontractor, warehouse,
                     seller_price=0.0, add_mto_route=False,
                     resupply_product_tmpls=None, activate=True):
        """Split *bom* so that *operation* is performed by *subcontractor*.

        The original Bill of Materials is always kept as the one producing the final product,
        so that its manufacturing history stays reachable. When *activate* is False the
        generated records stay archived until the related ECO is applied. Returns the chain.
        """
        operations_before, operations_after = self._split_route(bom, operation)
        self._check_operation_categories(operation, operations_before, operations_after)
        lines_before, lines_operation, lines_after = self._split_components(
            bom, operation, operations_before, operations_after)

        chain = self.create({
            'company_id': bom.company_id.id,
            'warehouse_id': warehouse.id,
            'subcontractor_id': subcontractor.id,
            'final_product_tmpl_id': bom.product_tmpl_id.id,
            'anchor_product_tmpl_id': bom.product_tmpl_id.id,
            'operation_name': operation.name,
            'operation_category_id': operation.operation_category_id.id,
            'original_workcenter_id': operation.workcenter_id.id,
            'original_sequence': operation.sequence,
            'original_time_mode': operation.time_mode,
            'original_time_cycle_manual': operation.time_cycle_manual,
            'state': 'externalized',
        })

        phantoms = self.env['product.template']
        pre_phantom = self.env['product.template']
        if operations_before:
            pre_phantom = self._get_or_create_phantom_product(
                bom.product_tmpl_id,
                self._get_phantom_category(operation, operations_before, 'pre'),
                activate=activate,
            )
            phantoms |= pre_phantom
            pre_bom = self.env['mrp.bom'].create(dict(
                self._prepare_chain_bom_vals(bom, pre_phantom, 'normal', activate=activate),
                subcontracting_chain_id=chain.id,
            ))
            operation_mapping = self._relocate_operations(operations_before, pre_bom)
            self._relocate_component_lines(lines_before, pre_bom, operation_mapping)

        if operations_after:
            post_phantom = self._get_or_create_phantom_product(
                bom.product_tmpl_id,
                self._get_phantom_category(operation, operations_before, 'post'),
                activate=activate,
            )
            phantoms |= post_phantom
            subcontract_bom = self.env['mrp.bom'].create(dict(
                self._prepare_chain_bom_vals(
                    bom, post_phantom, 'subcontract', subcontractor, activate=activate),
                subcontracting_chain_id=chain.id,
            ))
            self._relocate_component_lines(lines_operation, subcontract_bom)
            lines_operation.unlink()
            # The original BoM keeps producing the final product with the remaining operations.
            bom.write({'subcontracting_chain_id': chain.id})
            self._add_component_line(bom, post_phantom, bom.product_qty)
            chain.anchor_product_tmpl_id = post_phantom
        else:
            subcontract_bom = bom
            lines_operation.write({'operation_id': False})

        # The routing has to leave the original BoM before it can become a subcontracting one:
        # Odoo forbids operations on a Bill of Materials of type Subcontracting.
        lines_before.unlink()
        operations_before.unlink()
        if operation:
            operation.unlink()

        if not operations_after:
            # Nothing happens after the subcontractor, so the original BoM becomes the
            # subcontracted one and directly produces the final product.
            bom.write({
                'type': 'subcontract',
                'subcontractor_ids': [(6, 0, subcontractor.ids)],
                'subcontracting_chain_id': chain.id,
            })

        if pre_phantom:
            self._add_component_line(subcontract_bom, pre_phantom, bom.product_qty)

        chain.phantom_product_tmpl_ids = [(6, 0, phantoms.ids)]
        chain._setup_anchor_product(seller_price=seller_price, add_mto_route=add_mto_route)
        if resupply_product_tmpls is None:
            resupply_product_tmpls = subcontract_bom.bom_line_ids.product_id.product_tmpl_id
        chain._apply_resupply_route(resupply_product_tmpls | pre_phantom)
        chain._sync_component_lines()
        return chain

    @api.model
    def _add_component_line(self, bom, product_tmpl, quantity):
        # While an ECO is pending the intermediate product is still archived, so its variant
        # has to be resolved explicitly.
        variant = product_tmpl.with_context(active_test=False).product_variant_id
        self.env['mrp.bom.line'].create({
            'bom_id': bom.id,
            'product_id': variant.id,
            'product_qty': quantity,
            'product_uom_id': product_tmpl.uom_id.id,
        })

    def _get_subcontracted_bom(self):
        self.ensure_one()
        return self.bom_ids.filtered(lambda bom: bom.type == 'subcontract')[:1]

    def _sync_component_lines(self):
        """Refresh the component checklist from the real content of the subcontracted BoM."""
        for chain in self:
            subcontract_bom = chain._get_subcontracted_bom()
            products = subcontract_bom.bom_line_ids.product_id.product_tmpl_id
            chain.component_line_ids.unlink()
            chain.component_line_ids = [
                (0, 0, {'product_tmpl_id': product_tmpl.id}) for product_tmpl in products
            ]
            chain.last_verified_date = fields.Datetime.now()

    # ------------------------------------------------------------------
    # Internalization engine
    # ------------------------------------------------------------------

    def _get_final_bom(self):
        self.ensure_one()
        final_bom = self.bom_ids.filtered(
            lambda bom: bom.product_tmpl_id == self.final_product_tmpl_id and bom.active)[:1]
        if not final_bom:
            raise UserError(_(
                'The Bill of Materials producing %s is no longer part of this chain.',
                self.final_product_tmpl_id.display_name,
            ))
        return final_bom

    def _build_internalization_plan(self, target_bom=None):
        """Describe the single Bill of Materials that would replace this chain.

        Nothing is written: the caller shows the result for review before applying it. The
        target already carries the content of the final Bill of Materials, so only the
        intermediate stages need to be merged into it.
        """
        self.ensure_one()
        final_bom = self._get_final_bom()
        target = target_bom or final_bom
        source_boms = self.bom_ids - final_bom - target
        phantom_products = self.phantom_product_tmpl_ids.with_context(
            active_test=False).product_variant_ids
        return {
            'final_bom': final_bom,
            'target_bom': target,
            'operations': source_boms.operation_ids.sorted(lambda op: (op.sequence, op.id)),
            'component_lines': source_boms.bom_line_ids.filtered(
                lambda line: line.product_id not in phantom_products),
        }

    def _internalize(self, workcenter, target_bom=None, component_lines=None,
                     operation_sequences=None, activate=True):
        """Merge the chain back into a single in-house Bill of Materials.

        The current content of the chain is preserved: components added while the operation
        was externalized are carried over instead of being rolled back. When *activate* is
        False the merge is prepared on a revision and only takes effect once its Engineering
        Change Order is applied.
        """
        self.ensure_one()
        plan = self._build_internalization_plan(target_bom=target_bom)
        target = plan['target_bom']
        lines_to_keep = component_lines if component_lines is not None else plan['component_lines']

        self.env['mrp.routing.workcenter'].create({
            'bom_id': target.id,
            'name': self.operation_name or self.operation_category_id.name,
            'workcenter_id': workcenter.id,
            'sequence': self.original_sequence,
            'time_mode': self.original_time_mode or 'manual',
            'time_cycle_manual': self.original_time_cycle_manual,
            'operation_category_id': self.operation_category_id.id,
        })
        operation_mapping = {}
        for operation in plan['operations']:
            operation_mapping[operation] = operation.copy({
                'bom_id': target.id,
                'blocked_by_operation_ids': [(5, 0, 0)],
            })
        for operation, sequence in (operation_sequences or {}).items():
            operation_mapping.get(operation, operation).sequence = sequence

        for line in lines_to_keep:
            self._relocate_component_lines(line, target, operation_mapping)

        target.write({
            'type': 'normal',
            'subcontractor_ids': [(5, 0, 0)],
            'subcontracting_chain_id': self.id,
        })
        # Drop the intermediate product line that used to feed the subcontracted stage.
        target.bom_line_ids.filtered(
            lambda line: line.product_id.product_tmpl_id in self.phantom_product_tmpl_ids
        ).unlink()

        if activate:
            self._finalize_internalization(target)
        else:
            self.pending_internalization_bom_id = target.id
        return target

    def _finalize_internalization(self, final_bom):
        """Archive what the chain replaced, once the merge actually reaches production."""
        self.ensure_one()
        (self.bom_ids - final_bom).write({'active': False})
        self.phantom_product_tmpl_ids.write({'active': False})
        self.write({
            'state': 'internalized',
            'internalized_bom_id': final_bom.id,
            'pending_internalization_bom_id': False,
        })

    def _on_eco_applied(self):
        """Make the records prepared on a BoM revision live."""
        for chain in self:
            if chain.pending_internalization_bom_id:
                chain._finalize_internalization(chain.pending_internalization_bom_id)
                continue
            chain.bom_ids.filtered(lambda bom: not bom.active).write({'active': True})
            chain.phantom_product_tmpl_ids.filtered(
                lambda tmpl: not tmpl.active).write({'active': True})

    # ------------------------------------------------------------------
    # Action methods
    # ------------------------------------------------------------------

    def action_view_purchase_orders(self):
        self.ensure_one()
        orders = self.env['purchase.order.line'].search([
            ('product_id', 'in', self.anchor_product_tmpl_id.product_variant_ids.ids),
            ('order_id.partner_id', '=', self.subcontractor_id.id),
        ]).order_id
        return {
            'name': _('Purchase Orders'),
            'type': 'ir.actions.act_window',
            'res_model': 'purchase.order',
            'view_mode': 'tree,form',
            'domain': [('id', 'in', orders.ids)],
        }

    def action_view_receipts(self):
        self.ensure_one()
        pickings = self.env['purchase.order.line'].search([
            ('product_id', 'in', self.anchor_product_tmpl_id.product_variant_ids.ids),
            ('order_id.partner_id', '=', self.subcontractor_id.id),
        ]).move_ids.picking_id
        return {
            'name': _('Receipts'),
            'type': 'ir.actions.act_window',
            'res_model': 'stock.picking',
            'view_mode': 'tree,form',
            'domain': [('id', 'in', pickings.ids)],
        }

    def action_view_resupplies(self):
        self.ensure_one()
        return {
            'name': _('Subcontractor Resupplies'),
            'type': 'ir.actions.act_window',
            'res_model': 'stock.picking',
            'view_mode': 'tree,form',
            'domain': [
                ('partner_id', '=', self.subcontractor_id.id),
                ('picking_type_id', '=', self.warehouse_id.subcontracting_resupply_type_id.id),
            ],
        }

    def action_verify(self):
        self._sync_component_lines()
        return True

    def action_open_internalization_wizard(self):
        self.ensure_one()
        if self.state != 'externalized':
            raise UserError(_('Only an externalized chain can be internalized.'))
        return {
            'name': _('Internalize Operation'),
            'type': 'ir.actions.act_window',
            'res_model': 'mrp.subcontracting.internalization',
            'view_mode': 'form',
            'target': 'new',
            'context': {'default_chain_id': self.id},
        }
