# -*- coding: utf-8 -*-
{
    "name": "Econovo - User Warehouse Restriction",
    "version": "17.0.1.2.0",
    "category": "Inventory",
    "summary": "Granular warehouse access control with 10-flag permission matrix per user/warehouse",
    "author": "Jose D. Leonett",
    "website": "https://github.com/josedleonett",
    "license": "AGPL-3",
    "depends": ["stock"],
    "data": [
        "security/econovo_user_warehouse_restriction_groups.xml",
        "security/econovo_user_warehouse_restriction_security.xml",
        "wizard/bypass_info_wizard_views.xml",
        "security/ir.model.access.csv",
        "views/stock_warehouse_views.xml",
        "views/warehouse_user_permission_views.xml",
        "views/stock_location_views.xml",
        "views/res_users_views.xml",
    ],
    "post_init_hook": "post_init_hook",
    "installable": True,
    "auto_install": False,
    "application": False,
}