from odoo import _, api, fields, models
from odoo.exceptions import ValidationError
from odoo.tools.safe_eval import safe_eval


class EconovoApprovalRule(models.Model):
    """Routing rules for activity-based approval of payments and journal entries.

    One rule set covers both account.payment and account.move (move_type='entry').
    The target_model field determines which records the rule applies to.

    Rules are evaluated in sequence order; ALL matching rules generate an activity
    (multiple approvers can be required for the same document).
    """

    _name = 'econovo.approval.rule'
    _description = 'Approval Routing Rule'
    _order = 'sequence, id'

    name = fields.Char(required=True, translate=True)
    sequence = fields.Integer(default=10)
    active = fields.Boolean(default=True)
    target_model = fields.Selection(
        selection=[
            ('account.payment', 'Payment'),
            ('account.move', 'Journal Entry'),
        ],
        string='Applies To',
        required=True,
        default='account.payment',
        help='Model against which the domain is evaluated.',
    )
    domain = fields.Char(
        default='[]',
        help=(
            'Odoo domain evaluated against the target model records. '
            'The activity is created only when the record matches this domain.'
        ),
    )
    user_id = fields.Many2one(
        'res.users',
        string='Approver',
        required=True,
        help='User that receives the approval activity.',
    )
    supervisor_ids = fields.Many2many(
        'res.users',
        string='Supervisors',
        help=(
            'Users who can approve activities generated by this rule in addition '
            'to the primary approver.  Supervisors can complete a pending '
            'approval activity even when it is assigned to the primary approver.'
        ),
    )
    note = fields.Text(
        string='Internal Notes',
        help='Optional explanation of the routing logic for this rule.',
    )

    @api.constrains('domain')
    def _check_domain(self):
        """Validate that the domain string is syntactically correct."""
        for rule in self:
            if rule.domain:
                try:
                    safe_eval(rule.domain, mode='eval')
                except Exception as e:
                    raise ValidationError(
                        _('Invalid domain for rule "%s": %s', rule.name, e)
                    ) from e

    @api.model
    def _get_supervisors_for_activity(self, activity):
        """Return the set of supervisor UIDs authorized to complete an approval activity.

        Evaluates all active rules for the activity's model whose primary approver
        matches the activity's assigned user, then verifies that the related record
        still satisfies each rule's domain (dynamic lookup — Approach A).

        Returns an empty set when no matching rule is found, the related record
        no longer exists, or an exception occurs during domain evaluation.
        """
        if activity.res_model not in ('account.payment', 'account.move'):
            return set()

        rules = self.search([
            ('active', '=', True),
            ('target_model', '=', activity.res_model),
            ('user_id', '=', activity.user_id.id),
        ])
        if not rules:
            return set()

        try:
            record = self.env[activity.res_model].sudo().browse(activity.res_id)
            if not record.exists():
                return set()
        except Exception:
            return set()

        supervisor_ids = set()
        for rule in rules:
            domain = safe_eval(rule.domain or '[]')
            if not domain or record.filtered_domain(domain):
                supervisor_ids.update(rule.supervisor_ids.ids)
        return supervisor_ids
